CREATE DATABASE BD_VendaCDS_sql;

CREATE TABLE CLIENTE( 
		CLI_INT_ID INT NOT NULL IDENTITY(1,1),
		CLI_STR_NOME VARCHAR(70),
		CLI_STR_CPF VARCHAR(70),
		CLI_INT_DATANACIMENTO DATE,
		CLI_STR_EMAIL VARCHAR(70),
		CLI_INT_TELEFONE INT,
		CONSTRAINT PK_CLI_ID PRIMARY KEY(CLI_INT_ID),
		CONSTRAINT UK_CLI_STR_EMAIL UNIQUE (CLI_STR_EMAIL),
		CONSTRAINT UK_CLI_STR_CPF UNIQUE (CLI_STR_CPF),
		CONSTRAINT UK_CLI_INT_TELEFONE UNIQUE (CLI_INT_TELEFONE))

ALTER TABLE CLIENTE
ADD END_INT_ID INT NOT NULL,
CONSTRAINT FK_ENDERECO_CLIENTE_ID FOREIGN KEY(END_INT_ID)
	REFERENCES ENDERECO(END_INT_ID)

SELECT * FROM CLIENTE;

CREATE TABLE ESTADO(
	EST_INT_ID INT NOT NULL IDENTITY(1,1),
	EST_STR_DESC VARCHAR(70),
	EST_STR_SIGLA CHAR(2),
	CONSTRAINT PK_ESTADO_ID  PRIMARY KEY(EST_INT_ID)
) 

SELECT * FROM ESTADO;

CREATE TABLE CIDADE (
	CID_INT_ID INT NOT NULL IDENTITY(1,1),
	CID_STR_DESC VARCHAR(70),
	EST_INT_ID INT NOT NULL,
	CONSTRAINT PK_CIDADE_ID  PRIMARY KEY(CID_INT_ID),
	CONSTRAINT FK_CIDADE_ESTADO_ID FOREIGN KEY(EST_INT_ID)
	REFERENCES ESTADO(EST_INT_ID)
)

SELECT * FROM CIDADE;

CREATE TABLE ENDERECO (
	END_INT_ID INT NOT NULL IDENTITY(1,1),
	END_STR_RUA VARCHAR(70),
	END_STR_BAIRO VARCHAR(70),
	END_INT_CEP INT,
	CID_INT_ID INT NOT NULL,
	CONSTRAINT PK_ENDERECO_ID  PRIMARY KEY(END_INT_ID),
	CONSTRAINT FK_ENDERECO_CIDADE_ID FOREIGN KEY(CID_INT_ID)
	REFERENCES CIDADE(CID_INT_ID)
)

CREATE TABLE PEDIDO_VENDA(
	PEV_INT_ID INT NOT NULL IDENTITY(1,1),
	PEV_INT_DATE DATETIME,
	PEV_INT_NUMERO INT,
	CONSTRAINT PK_PEDIDO_ID  PRIMARY KEY(PEV_INT_ID),
)

ALTER TABLE PEDIDO_VENDA
ADD CLI_INT_ID INT NOT NULL,
CONSTRAINT FK_PEDIDO_VENDA_CLIENTE_ID FOREIGN KEY(CLI_INT_ID)
	REFERENCES CLIENTE(CLI_INT_ID)

SELECT * FROM PEDIDO_VENDA;

CREATE TABLE PRODUTO(
	PRO_INT_ID INT NOT NULL IDENTITY(1,1),
	PRO_INT_PRECO INT,
	PRO_STR_NOME VARCHAR(70),
	PRO_INT_CODIGOBARRAS INT
	CONSTRAINT PK_PRODUTO_ID  PRIMARY KEY(PRO_INT_ID),
	CONSTRAINT UK_PRO_INT_CODIGOBARRAS UNIQUE (PRO_INT_CODIGOBARRAS),
)

ALTER TABLE PRODUTO
ADD GRA_INT_ID INT NOT NULL,
CONSTRAINT FK_GRAVADORA_PRODUTO_ID FOREIGN KEY(GRA_INT_ID)
	REFERENCES GRAVADORA(GRA_INT_ID)

SELECT * FROM PRODUTO

CREATE TABLE PED_PRO(
	PRO_INT_ID INT NOT NULL,
	PEV_INT_ID INT NOT NULL,
	CONSTRAINT FK_PED_PROD_PEV_ID FOREIGN KEY(PEV_INT_ID)
	REFERENCES PEDIDO_VENDA(PEV_INT_ID),
	CONSTRAINT FK_PED_PROD_PRO_ID FOREIGN KEY(PRO_INT_ID)
	REFERENCES PRODUTO(PRO_INT_ID)
)

SELECT * FROM PED_PRO

CREATE TABLE GRAVADORA(
	GRA_INT_ID INT NOT NULL IDENTITY(1,1),
	GRA_STR_ENDERECO VARCHAR(70) ,
	GRA_IN_CNPJ INT,
	GRA_INT_TELEFONE INT,
	GRA_STR_EMAIL VARCHAR(70)
	CONSTRAINT PK_GRAVADORA_ID  PRIMARY KEY(GRA_INT_ID),
	CONSTRAINT UK_GRA_INT_CNPJ UNIQUE (GRA_IN_CNPJ),
	CONSTRAINT UK_GRA_INT_TELEFONE UNIQUE (GRA_INT_TELEFONE),
	CONSTRAINT UK_GRA_STR_EMAIL UNIQUE (GRA_STR_EMAIL),
)

CREATE TABLE GENERO (
	GEN_INT_ID INT NOT NULL IDENTITY(1,1),
	GEN_STR_DESC VARCHAR(70),
	CONSTRAINT UK_GEN_STR_DESC UNIQUE (GEN_STR_DESC),
	CONSTRAINT PK_GEN_INT_ID PRIMARY KEY(GEN_INT_ID)
)

CREATE TABLE PRODUTO_GENERO (
	GEN_INT_ID INT NOT NULL,
	PRO_INT_ID INT NOT NULL,
	CONSTRAINT FK_PRODUTO_GENERO_GENERO FOREIGN KEY(GEN_INT_ID)
	REFERENCES GENERO(GEN_INT_ID),
	CONSTRAINT FK_PRODUTO_GENERO_PRODUTO FOREIGN KEY(PRO_INT_ID)
	REFERENCES PRODUTO(PRO_INT_ID)

)

CREATE TABLE INTERPRETE (
	INTER_INT_ID INT NOT NULL IDENTITY(1,1),
	INTER_STR_NOME VARCHAR(80)
	CONSTRAINT PK_INTER_INT_ID PRIMARY KEY (INTER_INT_ID)
)

CREATE TABLE PRODUTO_INTERPRETE (
	PRO_INT_ID INT NOT NULL,
	INTER_INT_ID INT NOT NULL,
	CONSTRAINT FK_PRODUTO_INTERPRETE_INTERPRETE FOREIGN KEY(INTER_INT_ID)
	REFERENCES INTERPRETE(INTER_INT_ID),
	CONSTRAINT FK_PRODUTO_INTERPRETE_PRODUTO FOREIGN KEY(PRO_INT_ID)
	REFERENCES PRODUTO(PRO_INT_ID)
)

CREATE TABLE MUSICA (
	MUS_INT_ID INT NOT NULL IDENTITY(1,1),
	MUS_STR_NOME VARCHAR(80),
	MUS_INT_FAIXA INT,
	MUS_STR_ALBUM VARCHAR(70),
	MUS_INT_TEMPO INT
	CONSTRAINT PK_MUS_INT_ID PRIMARY KEY (MUS_INT_ID)
)

CREATE TABLE MUSICA_INTERPRETE (
	INTER_INT_ID INT NOT NULL,
	MUS_INT_ID INT NOT NULL,
	CONSTRAINT FK_MUSICA_INTERPRETE_INTER FOREIGN KEY (INTER_INT_ID)
	REFERENCES INTERPRETE(INTER_INT_ID),
	CONSTRAINT FK_MUSICA_INTERPRETE_MUSICA FOREIGN KEY(MUS_INT_ID)
	REFERENCES MUSICA(MUS_INT_ID)
)

CREATE TABLE COMPOSITOR (
	COM_INT_ID INT NOT NULL IDENTITY(1,1),
	COM_STR_NOME VARCHAR(70),
	COM_STR_EMAIL VARCHAR(70)
	CONSTRAINT PK_COM_INT_ID PRIMARY KEY (COM_INT_ID),
	CONSTRAINT UK_COM_STR_EMAIL UNIQUE (COM_STR_EMAIL)
)

CREATE TABLE COMPOSITOR_MUSICA (
	MUS_INT_ID INT NOT NULL,
	COM_INT_ID INT NOT NULL,
	CONSTRAINT FK_COMPOSITOR_MUSICA_MUSICA FOREIGN KEY(MUS_INT_ID)
	REFERENCES MUSICA(MUS_INT_ID),
	CONSTRAINT FK_COMPOSITOR_MUSICA_COMPOSITOR FOREIGN KEY(COM_INT_ID)
	REFERENCES COMPOSITOR(COM_INT_ID),
)










