CREATE DATABASE EX8

CREATE TABLE ESTADO (
  EST_INT_ID INTEGER NOT NULL IDENTITY(1,1),
  EST_STR_SIGLA CHAR(2),
  EST_STR_DESC VARCHAR(70),
  CONSTRAINT PK_EST_INT_ID PRIMARY KEY (EST_INT_ID)
);

CREATE TABLE CIDADE (
  CID_INT_ID INTEGER NOT NULL IDENTITY(1,1),
  EST_INT_ID INTEGER NOT NULL,
  CID_STR_DES VARCHAR(70),
  CONSTRAINT PK_CID_INT_ID PRIMARY KEY (CID_INT_ID),
  CONSTRAINT FK_CIDADE_ESTADO FOREIGN KEY (EST_INT_ID) REFERENCES ESTADO (EST_INT_ID)
);

CREATE TABLE ENDEREÇO (
  END_INT_ID INTEGER NOT NULL IDENTITY(1,1),
  CID_INT_ID INTEGER NOT NULL,
  END_STR_RUA VARCHAR(70),
  END_STR_BAIRRO VARCHAR(70),
  END_INT_CEP INTEGER,
  END_STR_COMPLEMENTO VARCHAR(70),
  CONSTRAINT PK_END_INT_ID PRIMARY KEY (END_INT_ID),
  CONSTRAINT FK_ENDEREÇO_CIDADE FOREIGN KEY (CID_INT_ID) REFERENCES CIDADE (CID_INT_ID)
);

CREATE TABLE SOCIO (
  SOC_INT_ID INTEGER NOT NULL IDENTITY(1,1),
  END_INT_ID INTEGER NOT NULL,
  SOC_STR_NOME VARCHAR(70),
  SOC_DAT_DATA_NACIMENTO DATE,
  CONSTRAINT PK_SOC_INT_ID PRIMARY KEY (SOC_INT_ID),
  CONSTRAINT FK_SOCIO_ENDEREÇO FOREIGN KEY (END_INT_ID) REFERENCES ENDEREÇO (END_INT_ID)
);

CREATE TABLE PILOTO (
  PIL_INT_ID INTEGER NOT NULL IDENTITY(1,1),
  SOC_INT_ID INTEGER NOT NULL,
  PIL_INT_BREVE INTEGER,
  CONSTRAINT PK_PIL_INT_ID PRIMARY KEY (PIL_INT_ID),
  CONSTRAINT FK_PILOTO_SOCIO FOREIGN KEY (SOC_INT_ID) REFERENCES SOCIO (SOC_INT_ID),
  CONSTRAINT UK_PIL_INT_BREVE_UNIQUE UNIQUE (PIL_INT_BREVE)
);

CREATE TABLE ALUNO (
  ALU_INT_ID INTEGER NOT NULL IDENTITY(1,1),
  SOC_INT_ID INTEGER NOT NULL,
  CONSTRAINT PK_ALU_INT_ID PRIMARY KEY (ALU_INT_ID),
  CONSTRAINT FK_ALUNO_SOCIO FOREIGN KEY (SOC_INT_ID) REFERENCES SOCIO (SOC_INT_ID)
);

CREATE TABLE INSTRUTOR (
  INS_INT_ID INTEGER NOT NULL IDENTITY(1,1),
  SOC_INT_ID INTEGER NOT NULL,
  PIL_INT_ID INTEGER NOT NULL,
  INS_STR_CURSO VARCHAR(70),
  INS_DAT_DIPLOMA DATE,
  INS_STR_INSTITUICAO VARCHAR(70),
  CONSTRAINT PK_INS_INT_ID PRIMARY KEY (INS_INT_ID),
  CONSTRAINT FK_INSTRUTOR_SOCIO FOREIGN KEY (SOC_INT_ID) REFERENCES SOCIO (SOC_INT_ID),
  CONSTRAINT FK_INSTRUTOR_PILOTO FOREIGN KEY (PIL_INT_ID) REFERENCES PILOTO (PIL_INT_ID)
);

CREATE TABLE SAIDA (
  SAI_INT_ID INTEGER NOT NULL IDENTITY(1,1),
  ALU_INT_ID INTEGER NOT NULL,
  INS_INT_ID INTEGER NOT NULL,
  SAI_DAT_SAIDA DATE,
  SAI_HOR_HORA_SAIDA TIME,
  SAI_HOR_HORA_CHEGADA TIME,
  SAI_STR_PARECER VARCHAR(70),
  CONSTRAINT PK_SAI_INT_ID PRIMARY KEY (SAI_INT_ID),
  CONSTRAINT FK_SAIDA_ALUNO FOREIGN KEY (ALU_INT_ID) REFERENCES ALUNO (ALU_INT_ID),
  CONSTRAINT FK_SAIDA_INSTRUTOR FOREIGN KEY (INS_INT_ID) REFERENCES INSTRUTOR (INS_INT_ID)
);
