CREATE TABLE ESTADO (
  EST_INT_ID INTEGER   NOT NULL ,
  EST_STR_SIGLA CHAR(2)    ,
  EST_STR_DES VARCHAR(70)      ,
PRIMARY KEY(EST_INT_ID));




CREATE TABLE SOLICITANTE (
  SOL_INT_ID INTEGER   NOT NULL ,
  SOL_STR_NOME VARCHAR(80)    ,
  SOL_STR_EMAIL VARCHAR(80)    ,
  SOL_STR_TELEFONE INTEGER      ,
PRIMARY KEY(SOL_INT_ID)    );


CREATE UNIQUE INDEX UK_SOL_EMAIL ON SOLICITANTE (SOL_STR_EMAIL);
CREATE UNIQUE INDEX UK_SOL_TELEFONE ON SOLICITANTE (SOL_STR_TELEFONE);




CREATE TABLE CIDADE (
  CID_INT_ID INTEGER   NOT NULL ,
  EST_INT_ID INTEGER   NOT NULL ,
  CID_STR_DES VARCHAR(70)      ,
PRIMARY KEY(CID_INT_ID)  ,
  FOREIGN KEY(EST_INT_ID)
    REFERENCES ESTADO(EST_INT_ID));


CREATE INDEX CIDADE_FKIndex1 ON CIDADE (EST_INT_ID);


CREATE INDEX IFK_FK_CIDADE_ESTADO ON CIDADE (EST_INT_ID);


CREATE TABLE ENDEREÇO (
  END_INT_ID INTEGER   NOT NULL ,
  END_CID_INT_ID INTEGER   NOT NULL ,
  END_STR_RUA VARCHAR(70)    ,
  END_STR_BAIRO VARCHAR(70)    ,
  END_INT_CEP INTEGER    ,
  END_STR_COMPLEMENTO VARCHAR(90)      ,
PRIMARY KEY(END_INT_ID)  ,
  FOREIGN KEY(END_CID_INT_ID)
    REFERENCES CIDADE(CID_INT_ID));


CREATE INDEX ENDEREÇO_FKIndex1 ON ENDEREÇO (END_CID_INT_ID);


CREATE INDEX IFK_FK_ENDERECO_CIDADE ON ENDEREÇO (END_CID_INT_ID);


CREATE TABLE CONTATO (
  CON_INT_ID INTEGER   NOT NULL ,
  END_INT_ID INTEGER   NOT NULL ,
  CON_INT_TELEFONE INTEGER    ,
  CON_STR_EMAIL VARCHAR(80)      ,
PRIMARY KEY(CON_INT_ID)    ,
  FOREIGN KEY(END_INT_ID)
    REFERENCES ENDEREÇO(END_INT_ID));


CREATE INDEX UK_CON_TELEFONE ON CONTATO (CON_INT_TELEFONE);
CREATE INDEX CONTATO_FKIndex1 ON CONTATO (END_INT_ID);


CREATE INDEX IFK_FK_ENDERECO_CONTATO ON CONTATO (END_INT_ID);


CREATE TABLE ADVOGADA (
  ADV_INT_ID INTEGER   NOT NULL ,
  CON_INT_ID INTEGER   NOT NULL ,
  ADV_STR_NOME VARCHAR      ,
PRIMARY KEY(ADV_INT_ID)  ,
  FOREIGN KEY(CON_INT_ID)
    REFERENCES CONTATO(CON_INT_ID));


CREATE INDEX ADVOGADA_FKIndex1 ON ADVOGADA (CON_INT_ID);


CREATE INDEX IFK_FK_CONTATO_ADVOGADA ON ADVOGADA (CON_INT_ID);


CREATE TABLE FORMULARIO (
  FOR_INT_ID INTEGER   NOT NULL ,
  ADV_INT_ID INTEGER   NOT NULL ,
  SOLICITANTE_SOL_INT_ID INTEGER   NOT NULL ,
  FOR_STR_ASSUNTO VARCHAR(80)    ,
  FOR_STR_MENSAGEM VARCHAR()80)      ,
PRIMARY KEY(FOR_INT_ID)    ,
  FOREIGN KEY(SOLICITANTE_SOL_INT_ID)
    REFERENCES SOLICITANTE(SOL_INT_ID),
  FOREIGN KEY(ADV_INT_ID)
    REFERENCES ADVOGADA(ADV_INT_ID));


CREATE INDEX FORMULARIO_FKIndex1 ON FORMULARIO (SOLICITANTE_SOL_INT_ID);
CREATE INDEX FORMULARIO_FKIndex2 ON FORMULARIO (ADV_INT_ID);


CREATE INDEX IFK_FK_SOLICITANTE_FORMULARIO ON FORMULARIO (SOLICITANTE_SOL_INT_ID);
CREATE INDEX IFK_FK_ADVOGADA_FORMULARIO ON FORMULARIO (ADV_INT_ID);


CREATE TABLE SERVICO_JURIDICO (
  SER_INT_ID INTEGER   NOT NULL ,
  ADV_INT_ID INTEGER   NOT NULL ,
  SER_STR_SERVICO VARCHAR()80)    ,
  SER_STR_DESCRICAO VARCHAR(80)      ,
PRIMARY KEY(SER_INT_ID)  ,
  FOREIGN KEY(ADV_INT_ID)
    REFERENCES ADVOGADA(ADV_INT_ID));


CREATE INDEX SERVICO_JURIDICO_FKIndex1 ON SERVICO_JURIDICO (ADV_INT_ID);


CREATE INDEX IFK_FK_ADVOGADA_SERVICO_JURIDI ON SERVICO_JURIDICO (ADV_INT_ID);



