
CREATE DATABASE SQL_PI;

CREATE TABLE ESTADO (
  EST_INT_ID INT NOT NULL IDENTITY(1,1),
  EST_STR_SIGLA CHAR(2),
  EST_STR_DES VARCHAR(70),
  CONSTRAINT PK_ESTADO PRIMARY KEY (EST_INT_ID)
);


CREATE TABLE SOLICITANTE (
  SOL_INT_ID INT NOT NULL IDENTITY(1,1),
  SOL_STR_NOME VARCHAR(80),
  SOL_STR_EMAIL VARCHAR(80),
  SOL_STR_TELEFONE BIGINT,
  CONSTRAINT PK_SOLICITANTE PRIMARY KEY (SOL_INT_ID),
  CONSTRAINT UK_SOLICITANTE_EMAIL UNIQUE (SOL_STR_EMAIL),
  CONSTRAINT UK_SOLICITANTE_TELEFONE UNIQUE (SOL_STR_TELEFONE)
);


CREATE TABLE CIDADE (
  CID_INT_ID INT NOT NULL IDENTITY(1,1),
  EST_INT_ID INT NOT NULL,
  CID_STR_DES VARCHAR(70),
  CONSTRAINT PK_CIDADE PRIMARY KEY (CID_INT_ID),
  CONSTRAINT FK_CIDADE_ESTADO FOREIGN KEY (EST_INT_ID) REFERENCES ESTADO(EST_INT_ID)
);

CREATE TABLE ENDERECO (
  END_INT_ID INT NOT NULL IDENTITY(1,1),
  END_CID_INT_ID INT NOT NULL,
  END_STR_RUA VARCHAR(70),
  END_STR_BAIRO VARCHAR(70),
  END_INT_CEP INT,
  END_STR_COMPLEMENTO VARCHAR(90),
  CONSTRAINT PK_ENDERECO PRIMARY KEY (END_INT_ID),
  CONSTRAINT FK_ENDERECO_CIDADE FOREIGN KEY (END_CID_INT_ID) REFERENCES CIDADE(CID_INT_ID)
);

CREATE TABLE CONTATO (
  CON_INT_ID INT NOT NULL IDENTITY(1,1),
  END_INT_ID INT NOT NULL,
  CON_INT_TELEFONE BIGINT,
  CON_STR_EMAIL VARCHAR(80),
  CONSTRAINT PK_CONTATO PRIMARY KEY (CON_INT_ID),
  CONSTRAINT FK_CONTATO_ENDERECO FOREIGN KEY (END_INT_ID) REFERENCES ENDERECO(END_INT_ID),
  CONSTRAINT UK_CONTATO_TELEFONE UNIQUE (CON_INT_TELEFONE)
);

CREATE TABLE ADVOGADA (
  ADV_INT_ID INT NOT NULL IDENTITY(1,1),
  CON_INT_ID INT NOT NULL,
  ADV_STR_NOME VARCHAR(100),
  CONSTRAINT PK_ADVOGADA PRIMARY KEY (ADV_INT_ID),
  CONSTRAINT FK_ADVOGADA_CONTATO FOREIGN KEY (CON_INT_ID) REFERENCES CONTATO(CON_INT_ID)
);

CREATE TABLE FORMULARIO (
  FOR_INT_ID INT NOT NULL IDENTITY(1,1),
  ADV_INT_ID INT NOT NULL,
  SOLICITANTE_SOL_INT_ID INT NOT NULL,
  FOR_STR_ASSUNTO VARCHAR(80),
  FOR_STR_MENSAGEM VARCHAR(800),
  CONSTRAINT PK_FORMULARIO PRIMARY KEY (FOR_INT_ID),
  CONSTRAINT FK_FORMULARIO_SOLICITANTE FOREIGN KEY (SOLICITANTE_SOL_INT_ID) REFERENCES SOLICITANTE(SOL_INT_ID),
  CONSTRAINT FK_FORMULARIO_ADVOGADA FOREIGN KEY (ADV_INT_ID) REFERENCES ADVOGADA(ADV_INT_ID)
);

CREATE TABLE SERVICO_JURIDICO (
  SER_INT_ID INT NOT NULL IDENTITY(1,1),
  ADV_INT_ID INT NOT NULL,
  SER_STR_SERVICO VARCHAR(80),
  SER_STR_DESCRICAO VARCHAR(80),
  CONSTRAINT PK_SERVICO_JURIDICO PRIMARY KEY (SER_INT_ID),
  CONSTRAINT FK_SERVICO_JURIDICO_ADVOGADA FOREIGN KEY (ADV_INT_ID) REFERENCES ADVOGADA(ADV_INT_ID)
);

INSERT INTO ESTADO (EST_STR_SIGLA, EST_STR_DES)
VALUES ('SP', 'São Paulo');

INSERT INTO CIDADE (EST_INT_ID, CID_STR_DES)
VALUES (1, 'São Paulo');

INSERT INTO ENDERECO (END_CID_INT_ID, END_STR_RUA, END_STR_BAIRO, END_INT_CEP, END_STR_COMPLEMENTO)
VALUES (1, 'Avenida Professor Vicente Rao, n.º 2.054', 'Campo Belo', 4636001, 'Próximo ao aeroporto');

INSERT INTO CONTATO (END_INT_ID, CON_INT_TELEFONE, CON_STR_EMAIL)
VALUES (1, 11999999999, 'monica@cordeiroadv.com.br');

INSERT INTO ADVOGADA (CON_INT_ID, ADV_STR_NOME)
VALUES (1, 'Mônica Cordeiro');

INSERT INTO SERVICO_JURIDICO (ADV_INT_ID, SER_STR_SERVICO, SER_STR_DESCRICAO)
VALUES (1, 'Desbloqueio de conta bancária', 'Atendimento para desbloqueio judicial de contas.');


INSERT INTO SOLICITANTE (SOL_STR_NOME, SOL_STR_EMAIL, SOL_STR_TELEFONE)
VALUES ('João Silva', 'joao.silva@email.com', 11988888888);

INSERT INTO FORMULARIO (ADV_INT_ID, SOLICITANTE_SOL_INT_ID, FOR_STR_ASSUNTO, FOR_STR_MENSAGEM)
VALUES (1, 1, 'Desbloqueio de conta bancária', 'Preciso de ajuda para desbloquear minha conta judicialmente.');