CREATE DATABASE BD_aula2_sql;
CREATE TABLE CADASTRO(
	CAD_INT_ID INT NOT NULL IDENTITY(1,1),
	CAD_STR_NOME VARCHAR(80),
	CAD_STR_CPF VARCHAR(11),
	CONSTRAINT PK_CAD_ID  PRIMARY KEY(CAD_INT_ID),
	CONSTRAINT UK_CAD_SIGLA UNIQUE (CAD_STR_CPF) 
);

SELECT * FROM CADASTRO;

