CREATE DATABASE EX3_SQL;

CREATE TABLE SALA  (
 SAL_INT_ID INT NOT NULL IDENTITY(1,1),
 SAL_INT_NUMERO_SALA INT
 CONSTRAINT PK_SAL_INT_ID PRIMARY KEY(SAL_INT_ID )
)

CREATE TABLE ANDAR(
 AND_INT_ID INT NOT NULL IDENTITY(1,1),
 SAL_INT_ID INT NOT NULL,
 AND_INT_NUMERO_ANDAR INT,
 CONSTRAINT PK_AND_INT_ID PRIMARY KEY(AND_INT_ID ),
)


CREATE TABLE CARGO  (
 CAR_INT_ID INT NOT NULL IDENTITY(1,1),
 CAR_STR_DESCRICAO VARCHAR(70)
 CONSTRAINT PK_CAR_INT_ID PRIMARY KEY(CAR_INT_ID ),
 CONSTRAINT UK_CAR_STR_DESCRICAO UNIQUE (CAR_STR_DESCRICAO)
)

CREATE TABLE DEPARTAMENTO(
  DEP_INT_ID INT NOT NULL IDENTITY(1,1),
  AND_INT_ID INT NOT NULL,
  SAL_INT_ID INT NOT NULL,
  DEP_STR_DESC VARCHAR(70),
   CONSTRAINT PK_DEP_INT_ID PRIMARY KEY(DEP_INT_ID ),
  CONSTRAINT FK_ANDAR_DEPARTAMENTO_ID FOREIGN KEY(AND_INT_ID)
	REFERENCES ANDAR(AND_INT_ID),
  CONSTRAINT FK_SALA_DEPARTAMENTO_ID FOREIGN KEY(SAL_INT_ID)
	REFERENCES SALA(SAL_INT_ID)
)

DROP TABLE DEPARTAMENTO

CREATE TABLE FUNCIONARIOS(
	FUN_INT_ID INT NOT NULL IDENTITY(1,1),
	FUN_STR_NOME VARCHAR(70),
	CAR_INT_ID INT NOT NULL,
	FUN_INT_CPF INTEGER,
	FUN_STR_SEXO VARCHAR(70),
	FUN_INT_DATANACIMENTO DATE
	CONSTRAINT FK_FUNCIONARIO_CARGO FOREIGN KEY (CAR_INT_ID)
	REFERENCES CARGO(CAR_INT_ID),
	CONSTRAINT PK_FUN_INT_ID PRIMARY KEY(FUN_INT_ID ),
)

ALTER TABLE FUNCIONARIOS
ADD DEP_INT_ID INT NOT NULL,
CONSTRAINT FK_FUNCIONARIO_DEPARTAMENTO FOREIGN KEY (DEP_INT_ID)
	REFERENCES DEPARTAMENTO(DEP_INT_ID)


CREATE TABLE HISTORICO_SALARIO(
	HIS_INT_ID INT NOT NULL IDENTITY(1,1),
	HIS_INT_SALARIOS_ANTERIORES INT,
	FUN_INT_ID INT NOT NULL,
	 CONSTRAINT PK_HIS_INT_ID PRIMARY KEY(HIS_INT_ID ),
CONSTRAINT FK_HISTORICO_SALARIO_FUNCIONARIO FOREIGN KEY (FUN_INT_ID)
	REFERENCES FUNCIONARIOS(FUN_INT_ID)
)

CREATE TABLE COMISADO(
	COM_INT_ID INT NOT NULL IDENTITY(1,1),
	COM_INT_VALOR_COMISSAO INT,
	FUN_INT_ID INT NOT NULL,
	 CONSTRAINT PK_COM_INT_ID PRIMARY KEY(COM_INT_ID ),
CONSTRAINT FK_COMISADO_FUNCIONARIO FOREIGN KEY (FUN_INT_ID)
	REFERENCES FUNCIONARIOS(FUN_INT_ID)
)EX