CREATE DATABASE BD_EX_AULA3;

CREATE TABLE MEDICAMENTO(
	MED_INT_ID INT NOT NULL IDENTITY(1,1),
	MED_STR_DESCRICAO VARCHAR(80),
	MED_INT_CODIGOBARRAS INT,
	CONSTRAINT PK_MEDICAMENTO_ID  PRIMARY KEY(MED_INT_ID),
	CONSTRAINT UK_MEDICAMENTO_CODIGOBARRAS UNIQUE(MED_INT_CODIGOBARRAS)
);

CREATE TABLE PACIENTE(
	PAC_INT_ID INT NOT NULL IDENTITY(1,1),
	PAC_STR_NOME VARCHAR(80),
	PAC_STR_CPF VARCHAR(11),
	CONSTRAINT PK_PACIENTE_ID  PRIMARY KEY(PAC_INT_ID),
	CONSTRAINT UK_PACIENTE_CPF UNIQUE(PAC_STR_CPF)
);

CREATE TABLE MEDICO(
	MEC_INT_ID INT NOT NULL IDENTITY(1,1),
	MEC_STR_NOME VARCHAR(80),
	MEC_STR_CPF VARCHAR(11),
	CONSTRAINT PK_MEDICO_ID  PRIMARY KEY(MEC_INT_ID),
	CONSTRAINT UK_MEDICO_CPF UNIQUE(MEC_STR_CPF)
);

CREATE TABLE CONSULTA(
	CON_INT_ID INT NOT NULL IDENTITY(1,1),
	MEC_INT_ID INT NOT NULL,
	PAC_INT_ID INT NOT NULL,
	CONSTRAINT PK_CONSULTA_ID  PRIMARY KEY(CON_INT_ID),
	CONSTRAINT FK_MEDICO_CONSULTA_ID FOREIGN KEY(MEC_INT_ID)
	REFERENCES MEDICO(MEC_INT_ID),
	CONSTRAINT FK_PACIENTE_CONSULTA_ID FOREIGN KEY(PAC_INT_ID)
	REFERENCES PACIENTE(PAC_INT_ID),
);

CREATE TABLE RECEITA(
	CON_INT_ID INT NOT NULL,
	MED_INT_ID INT NOT NULL,
	CONSTRAINT FK_MEDICAMENTO_RECEITA_ID FOREIGN KEY(MED_INT_ID)
	REFERENCES MEDICAMENTO(MED_INT_ID),
	CONSTRAINT FK_CONSULTA_RECEITA_ID FOREIGN KEY(CON_INT_ID)
	REFERENCES CONSULTA(CON_INT_ID),
);


