CREATE DATABASE BD_aula3_sql;
CREATE TABLE ESTADO(
	EST_INT_ID INT NOT NULL IDENTITY(1,1),
	EST_STR_DESCRICAO VARCHAR(80),
	EST_STR_SIGLA CHAR(2),
	CONSTRAINT PK_ESTADO_ID  PRIMARY KEY(EST_INT_ID),
	CONSTRAINT UK_EST_SIGLA UNIQUE (EST_STR_SIGLA) 
);

SELECT * FROM ESTADO;

CREATE TABLE CIDADE(
	CID_INT_ID INT NOT NULL IDENTITY(1,1),
	CID_STR_DESCRICAO VARCHAR(80),
	EST_INT_ID INT NOT NULL,
	CONSTRAINT PK_CIDADE_ID  PRIMARY KEY(CID_INT_ID),
	CONSTRAINT FK_CIDADE_ESTADO_ID FOREIGN KEY(EST_INT_ID)
	REFERENCES ESTADO(EST_INT_ID)
);


SELECT * FROM CIDADE;