CREATE DATABASE EX3_SQL;

CREATE TABLE SALA  (
 SAL_INT_ID INT NOT NULL IDENTITY(1,1),
 SAL_INT_NUMERO_SALA INT
 CONSTRAINT PK_SAL_INT_ID PRIMARY KEY(SAL_INT_ID )
)

CREATE TABLE ANDAR(
 AND_INT_ID INT NOT NULL IDENTITY(1,1),
 SAL_INT_ID INT NOT NULL,
 AND_INT_NUMERO_ANDAR INT,
 CONSTRAINT PK_AND_INT_ID PRIMARY KEY(AND_INT_ID ),
)


CREATE TABLE CARGO  (
 CAR_INT_ID INT NOT NULL IDENTITY(1,1),
 CAR_STR_DESCRICAO VARCHAR(70)
 CONSTRAINT PK_CAR_INT_ID PRIMARY KEY(CAR_INT_ID ),
 CONSTRAINT UK_CAR_STR_DESCRICAO UNIQUE (CAR_STR_DESCRICAO)
)

CREATE TABLE DEPARTAMENTO(
  DEP_INT_ID INT NOT NULL IDENTITY(1,1),
  AND_INT_ID INT NOT NULL,
  SAL_INT_ID INT NOT NULL,
  DEP_STR_DESC VARCHAR(70),
  CONSTRAINT FK_ANDAR_DEPARTAMENTO_ID FOREIGN KEY(AND_INT_ID)
	REFERENCES ANDAR(AND_INT_ID),
  CONSTRAINT FK_SALA_DEPARTAMENTO_ID FOREIGN KEY(SAL_INT_ID)
	REFERENCES SALA(SAL_INT_ID)
)