CREATE DATABASE EX_6;

CREATE TABLE ESTADO (
  EST_INT_ID INTEGER NOT NULL IDENTITY(1,1),
  EST_STR_SIGLA CHAR(2),
  EST_STR_DESC VARCHAR(70),
  CONSTRAINT PK_ESTADO_INT_ID PRIMARY KEY (EST_INT_ID),
  CONSTRAINT UK_ESTADO_SIGLA UNIQUE (EST_STR_SIGLA)
);

CREATE TABLE PLATAFORMA (
  PLA_INT_ID INTEGER NOT NULL IDENTITY(1,1),
  PLA_STR_NOME VARCHAR(70),
  CONSTRAINT PK_PLATAFORMA_INT_ID PRIMARY KEY (PLA_INT_ID),
  CONSTRAINT UK_PLATAFORMA_NOME UNIQUE (PLA_STR_NOME)
);

CREATE TABLE SEGMENTO (
  SEG_INT_ID INTEGER NOT NULL IDENTITY(1,1),
  SEG_STR_NOME VARCHAR(70),
  SEG_STR_DESCRICAO VARCHAR(70),
  CONSTRAINT PK_SEGMENTO_INT_ID PRIMARY KEY (SEG_INT_ID),
  CONSTRAINT UK_SEGMENTO_NOME UNIQUE (SEG_STR_NOME)
);

CREATE TABLE CIDADE (
  CID_INT_ID INTEGER NOT NULL IDENTITY(1,1),
  EST_INT_ID INTEGER NOT NULL,
  CID_STR_DES VARCHAR(70),
  CONSTRAINT PK_CIDADE_INT_ID PRIMARY KEY (CID_INT_ID),
  CONSTRAINT FK_CIDADE_ESTADO FOREIGN KEY (EST_INT_ID) REFERENCES ESTADO(EST_INT_ID)
);

CREATE TABLE ENDERECO (
  END_INT_ID INTEGER NOT NULL IDENTITY(1,1),
  CID_INT_ID INTEGER NOT NULL,
  END_STR_RUA VARCHAR(70),
  END_STR_BAIRRO VARCHAR(70),
  END_INT_CEP INTEGER,
  END_STR_COMPLEMENTO VARCHAR(70),
  CONSTRAINT PK_ENDERECO_INT_ID PRIMARY KEY (END_INT_ID),
  CONSTRAINT FK_ENDERECO_CIDADE FOREIGN KEY (CID_INT_ID) REFERENCES CIDADE(CID_INT_ID),
  CONSTRAINT UK_ENDERECO_CEP UNIQUE (END_INT_CEP)
);

CREATE TABLE CONSULTOR (
  CON_INT_ID INTEGER NOT NULL IDENTITY(1,1),
  END_INT_ID INTEGER NOT NULL,
  CON_STR_NOME VARCHAR(70),
  CON_INT_TELEFONE INTEGER,
  CONSTRAINT PK_CONSULTOR_INT_ID PRIMARY KEY (CON_INT_ID),
  CONSTRAINT FK_CONSULTOR_ENDERECO FOREIGN KEY (END_INT_ID) REFERENCES ENDERECO(END_INT_ID),
  CONSTRAINT UK_CONSULTOR_TELEFONE UNIQUE (CON_INT_TELEFONE)
);

CREATE TABLE USUARIO (
  USU_INT_ID INTEGER NOT NULL IDENTITY(1,1),
  END_INT_ID INTEGER NOT NULL,
  USU_STR_NOME VARCHAR(70),
  USU_STR_TELEFONE INTEGER,
  CONSTRAINT PK_USUARIO_INT_ID PRIMARY KEY (USU_INT_ID),
  CONSTRAINT FK_USUARIO_ENDERECO FOREIGN KEY (END_INT_ID) REFERENCES ENDERECO(END_INT_ID),
  CONSTRAINT UK_USUARIO_TELEFONE UNIQUE (USU_STR_TELEFONE)
);

CREATE TABLE EVENTO (
  EVE_INT_ID INTEGER NOT NULL IDENTITY(1,1),
  USU_INT_ID INTEGER NOT NULL,
  CON_INT_ID INTEGER NOT NULL,
  SEG_INT_ID INTEGER NOT NULL,
  PLA_INT_ID INTEGER NOT NULL,
  EVE_DAT_OCORRENCIA DATE,
  EVE_STR_PROBLEMA VARCHAR(70),
  EVE_STR_SOLUCAO VARCHAR(70),
  EVE_STR_STATUS VARCHAR(70),
  CONSTRAINT PK_EVENTO_INT_ID PRIMARY KEY (EVE_INT_ID),
  CONSTRAINT FK_EVENTO_USUARIO FOREIGN KEY (USU_INT_ID) REFERENCES USUARIO(USU_INT_ID),
  CONSTRAINT FK_EVENTO_CONSULTOR FOREIGN KEY (CON_INT_ID) REFERENCES CONSULTOR(CON_INT_ID),
  CONSTRAINT FK_EVENTO_SEGMENTO FOREIGN KEY (SEG_INT_ID) REFERENCES SEGMENTO(SEG_INT_ID),
  CONSTRAINT FK_EVENTO_PLATAFORMA FOREIGN KEY (PLA_INT_ID) REFERENCES PLATAFORMA(PLA_INT_ID)
);

CREATE TABLE COMENTARIO (
  COM_INT_ID INTEGER NOT NULL IDENTITY(1,1),
  USU_INT_ID INTEGER NOT NULL,
  EVE_INT_ID INTEGER NOT NULL,
  COM_STR_TEXTO VARCHAR(70),
  COM_DAT_DATA DATE,
  CONSTRAINT PK_COMENTARIO_INT_ID PRIMARY KEY (COM_INT_ID),
  CONSTRAINT FK_COMENTARIO_USUARIO FOREIGN KEY (USU_INT_ID) REFERENCES USUARIO(USU_INT_ID),
  CONSTRAINT FK_COMENTARIO_EVENTO FOREIGN KEY (EVE_INT_ID) REFERENCES EVENTO(EVE_INT_ID)
);
