CREATE DATABASE BD_EX_AULA6;


CREATE TABLE ESTADO (
  EST_INT_ID INT NOT NULL IDENTITY(1,1),
  EST_STR_SIGLA CHAR(2),
  EST_STR_DES VARCHAR(70),
  CONSTRAINT PK_EST_INT_ID PRIMARY KEY(EST_INT_ID)
);

CREATE TABLE CIDADE (
  CID_INT_ID INT NOT NULL IDENTITY(1,1),
  EST_INT_ID INT NOT NULL,
  CID_STR_DES VARCHAR(70),
  CONSTRAINT PK_CID_INT_ID PRIMARY KEY(CID_INT_ID),
  CONSTRAINT FK_ENDERECO_ESTADO_ID FOREIGN KEY(EST_INT_ID) REFERENCES ESTADO(EST_INT_ID)
);

CREATE TABLE ENDEREÇO (
  END_INT_ID INT NOT NULL IDENTITY(1,1),
  CID_INT_ID INT NOT NULL,
  END_STR_RUA VARCHAR(70),
  END_STR_BAIRO VARCHAR(70),
  END_INT_CEP INT,
  CONSTRAINT PK_END_INT_ID PRIMARY KEY(END_INT_ID),
  CONSTRAINT FK_ENDERECO_CIDADE_ID FOREIGN KEY(CID_INT_ID) REFERENCES CIDADE(CID_INT_ID)
);

CREATE TABLE PESSOA (
  PES_INT_ID INT NOT NULL IDENTITY(1,1),
  PES_STR_NOME VARCHAR(80),
  PES_STR_CPF VARCHAR(11),
  END_INT_ID INT NOT NULL,
  CONSTRAINT PK_PESSOA_ID PRIMARY KEY(PES_INT_ID),
  CONSTRAINT UK_PESSOA_CPF UNIQUE(PES_STR_CPF),
  CONSTRAINT FK_ENDERECO_PESSOA FOREIGN KEY(END_INT_ID) REFERENCES ENDEREÇO(END_INT_ID)
);

CREATE TABLE PACIENTE (
  PAC_INT_ID INT NOT NULL IDENTITY(1,1),
  PES_INT_ID INT NOT NULL,
  CONSTRAINT PK_PACIENTE_ID PRIMARY KEY(PAC_INT_ID),
  CONSTRAINT FK_PESSOA_PACIENTE_ID FOREIGN KEY(PES_INT_ID) REFERENCES PESSOA(PES_INT_ID)
);

CREATE TABLE MEDICO (
  MEC_INT_ID INT NOT NULL IDENTITY(1,1),
  MEC_STR_NOME VARCHAR(80),
  MEC_STR_CRM VARCHAR(11),
  CONSTRAINT PK_MEDICO_ID PRIMARY KEY(MEC_INT_ID),
  CONSTRAINT UK_MEDICO_CRM UNIQUE(MEC_STR_CRM)
);

CREATE TABLE CONSULTA (
  CON_INT_ID INT NOT NULL IDENTITY(1,1),
  MEC_INT_ID INT NOT NULL,
  PAC_INT_ID INT NOT NULL,
  CONSTRAINT PK_CONSULTA_ID PRIMARY KEY(CON_INT_ID),
  CONSTRAINT FK_MEDICO_CONSULTA_ID FOREIGN KEY(MEC_INT_ID) REFERENCES MEDICO(MEC_INT_ID),
  CONSTRAINT FK_PACIENTE_CONSULTA_ID FOREIGN KEY(PAC_INT_ID) REFERENCES PACIENTE(PAC_INT_ID)
);

CREATE TABLE MEDICAMENTO (
  MED_INT_ID INT NOT NULL IDENTITY(1,1),
  MED_STR_DESCRICAO VARCHAR(80),
  MED_INT_CODIGOBARRAS INT,
  CONSTRAINT PK_MEDICAMENTO_ID PRIMARY KEY(MED_INT_ID),
  CONSTRAINT UK_MEDICAMENTO_CODIGOBARRAS UNIQUE(MED_INT_CODIGOBARRAS)
);

CREATE TABLE RECEITA (
  CON_INT_ID INT NOT NULL,
  MED_INT_ID INT NOT NULL,
  CONSTRAINT FK_CONSULTA_RECEITA_ID FOREIGN KEY(CON_INT_ID) REFERENCES CONSULTA(CON_INT_ID),
  CONSTRAINT FK_MEDICAMENTO_RECEITA_ID FOREIGN KEY(MED_INT_ID) REFERENCES MEDICAMENTO(MED_INT_ID)
);