CREATE DATABASE EX4_SQL

CREATE TABLE CARGO(
CAR_INT_ID INT NOT NULL IDENTITY(1,1),
CAR_STR_NOME VARCHAR(70),
CONSTRAINT PK_CAR_INT_ID PRIMARY KEY(CAR_INT_ID)
)  

CREATE TABLE FUNCIONARIO (
	FUN_INT_ID INT NOT NULL IDENTITY(1,1),
	FUN_STR_NOME VARCHAR(70),
	FUN_STR_STATUS_DISPONIVEL VARCHAR(70)
	CONSTRAINT PK_FUN_INT_ID PRIMARY KEY (FUN_INT_ID)
)

CREATE TABLE PROJETO (
	PRO_INT_ID INT NOT NULL IDENTITY(1,1),
	PRO_STR_NOME VARCHAR(70),
	PRO_STR_DESCRICAO VARCHAR(70),
	PRO_DAT_DATAINICIO DATE,
	PRO_DAT_DATAFIM DATE,
	CONSTRAINT PK_PRO_INT_ID PRIMARY KEY(PRO_INT_ID)
)

CREATE TABLE ALOCACAO (
	ALO_INT_ID INT NOT NULL IDENTITY(1,1),
	FUN_INT_ID INT NOT NULL,
	PRO_INT_ID INT NOT NULL,
	CONSTRAINT PK_ALO_INT PRIMARY KEY(ALO_INT_ID),
	CONSTRAINT FK_FUNCIONARIO_ALOCACAO FOREIGN KEY(FUN_INT_ID)
	REFERENCES FUNCIONARIO(FUN_INT_ID),
	CONSTRAINT FK_PROJETO_ALOCACAO FOREIGN KEY(PRO_INT_ID)
	REFERENCES PROJETO(PRO_INT_ID),
)


CREATE TABLE QUADRO_FUNCIONAL (
	QUA_INT_ID INT NOT NULL IDENTITY(1,1),
	FUN_INT_ID INT NOT NULL,
	CAR_INT_ID INT NOT NULL,
	CONSTRAINT PK_QUA_INT_ID PRIMARY KEY(QUA_INT_ID),
	CONSTRAINT FK_FUNCIONARIO_QUADRO_FUNCIONAL FOREIGN KEY(FUN_INT_ID)
	REFERENCES FUNCIONARIO(FUN_INT_ID),
	CONSTRAINT FK_CARGO_QUADRO FOREIGN KEY(CAR_INT_ID)
	REFERENCES CARGO(CAR_INT_ID),
)

INSERT INTO CARGO (CAR_STR_NOME)
VALUES ('Engenheiro'),
	   ('Arquiteto'),
	   ('Pedreiro')

SELECT * FROM CARGO

INSERT INTO FUNCIONARIO(FUN_STR_NOME , FUN_STR_STATUS_DISPONIVEL )
VALUES ('Jose','sim'),
	   ('Nauro', 'sim'),
	   ('Jailsom', 'náo')

SELECT * FROM FUNCIONARIO

INSERT INTO PROJETO (PRO_STR_NOME, PRO_STR_DESCRICAO, PRO_DAT_DATAINICIO , PRO_DAT_DATAFIM)
VALUES ('pedriox', 'predio de 4 andares', '22/02/2025', '22/02/2026'),
		('pedrioA', 'predio de 2 andares', '22/09/2025', '22/09/2026')

SELECT * FROM PROJETO

INSERT INTO ALOCACAO ( FUN_INT_ID, PRO_INT_ID)
VALUES (1,1),
	   (1,2),
	   (2,2),
	   (3,1),
	   (3,2)

INSERT INTO QUADRO_FUNCIONAL(FUN_INT_ID, CAR_INT_ID)
VALUES (1,1),
	   (2,2),
	   (3,3)

