CREATE DATABASE EX9

CREATE TABLE ESTADO (
  EST_INT_ID INTEGER NOT NULL IDENTITY(1,1),
  EST_STR_SIGLA CHAR(2),
  EST_STR_DESC VARCHAR(70),
  CONSTRAINT PK_EST_INT_ID PRIMARY KEY (EST_INT_ID)
);

CREATE TABLE INSTRUTOR (
  INS_INT_ID INTEGER NOT NULL IDENTITY(1,1),
  INS_STR_RG VARCHAR(9),
  INS_STR_NOME VARCHAR(7),
  INS_DAT_NASCIMENTO DATE,
  INS_STR_TITULACAO VARCHAR(70),
  CONSTRAINT PK_INS_INT_ID PRIMARY KEY (INS_INT_ID)
);

CREATE TABLE ATIVIDADE (
  ATI_INT_ID INTEGER NOT NULL IDENTITY(1,1),
  ATI_STR_DESCRICAO VARCHAR(70),
  CONSTRAINT PK_ATI_INT_ID PRIMARY KEY (ATI_INT_ID)
);

CREATE TABLE TELEFONE_INSTRUTOR (
  TEL_INT_ID INTEGER NOT NULL IDENTITY(1,1),
  INS_INT_ID INTEGER NOT NULL,
  TEL_INT_NUMEROS INTEGER,
  CONSTRAINT PK_TEL_INT_ID PRIMARY KEY (TEL_INT_ID),
  CONSTRAINT FK_TELEFONE_INSTRUTOR_INSTRUTOR FOREIGN KEY (INS_INT_ID) REFERENCES INSTRUTOR(INS_INT_ID),
  CONSTRAINT UK_TEL_INS_TEL_INT_NUMEROS UNIQUE (TEL_INT_NUMEROS)
);

CREATE TABLE CIDADE (
  CID_INT_ID INTEGER NOT NULL IDENTITY(1,1),
  EST_INT_ID INTEGER NOT NULL,
  CID_STR_DES VARCHAR(70),
  CONSTRAINT PK_CID_INT_ID PRIMARY KEY (CID_INT_ID),
  CONSTRAINT FK_CIDADE_ESTADO FOREIGN KEY (EST_INT_ID) REFERENCES ESTADO(EST_INT_ID)
);

CREATE TABLE ENDEREÇO (
  END_INT_ID INTEGER NOT NULL IDENTITY(1,1),
  CID_INT_ID INTEGER NOT NULL,
  END_STR_RUA VARCHAR(70),
  END_STR_BAIRRO VARCHAR(70),
  END_INT_CEP INTEGER,
  END_STR_COMPLEMENTO VARCHAR(70),
  CONSTRAINT PK_END_INT_ID PRIMARY KEY (END_INT_ID),
  CONSTRAINT FK_ENDEREÇO_CIDADE FOREIGN KEY (CID_INT_ID) REFERENCES CIDADE(CID_INT_ID)
);

CREATE TABLE ALUNO (
  ALU_INT_ID INTEGER NOT NULL IDENTITY(1,1),
  END_INT_ID INTEGER NOT NULL,
  ALU_STR_NOME VARCHAR(70),
  ALU_DAT_MATRICULA INTEGER,
  ALU_INT_TELEFONE INTEGER,
  ALU_DAT_NASCIMENTO DATE,
  ALU_FLO_ALTURA FLOAT,
  ALU_FLO_PESO FLOAT,
  CONSTRAINT PK_ALU_INT_ID PRIMARY KEY (ALU_INT_ID),
  CONSTRAINT FK_ALUNO_ENDEREÇO FOREIGN KEY (END_INT_ID) REFERENCES ENDEREÇO(END_INT_ID),
  CONSTRAINT UK_ALU_ALU_INT_TELEFONE UNIQUE (ALU_INT_TELEFONE)
);

CREATE TABLE MONITOR_ALUNO (
  MON_INT_ID INTEGER NOT NULL IDENTITY(1,1),
  ALU_INT_ID INTEGER NOT NULL,
  CONSTRAINT PK_MON_INT_ID PRIMARY KEY (MON_INT_ID),
  CONSTRAINT FK_MONITOR_ALUNO_ALUNO FOREIGN KEY (ALU_INT_ID) REFERENCES ALUNO(ALU_INT_ID)
);

CREATE TABLE TURMAS (
  TUR_INT_ID INTEGER NOT NULL IDENTITY(1,1),
  MON_INT_ID INTEGER NOT NULL,
  INS_INT_ID INTEGER NOT NULL,
  ATI_INT_ID INTEGER NOT NULL,
  TUR_INT_QTDE_ALUNOS INTEGER,
  TUR_STR_HORARIO TIME,
  TUR_INT_DURACAO INTEGER,
  TUR_DAT_INICIAL DATE,
  TUR_DAT_FINAL DATE,
  CONSTRAINT PK_TUR_INT_ID PRIMARY KEY (TUR_INT_ID),
  CONSTRAINT FK_TURMAS_INSTRUTOR FOREIGN KEY (INS_INT_ID) REFERENCES INSTRUTOR(INS_INT_ID),
  CONSTRAINT FK_TURMAS_ATIVIDADE FOREIGN KEY (ATI_INT_ID) REFERENCES ATIVIDADE(ATI_INT_ID),
  CONSTRAINT FK_TURMAS_MONITOR_ALUNO FOREIGN KEY (MON_INT_ID) REFERENCES MONITOR_ALUNO(MON_INT_ID)
);

CREATE TABLE MATRICULA (
  MAT_INT_ID INTEGER NOT NULL IDENTITY(1,1),
  TUR_INT_ID INTEGER NOT NULL,
  ALUNO_ALU_INT_ID INTEGER NOT NULL,
  MAT_INT_AUSENCIAS INTEGER,
  CONSTRAINT PK_MAT_INT_ID PRIMARY KEY (MAT_INT_ID),
  CONSTRAINT FK_MATRICULA_ALUNO FOREIGN KEY (ALUNO_ALU_INT_ID) REFERENCES ALUNO(ALU_INT_ID),
  CONSTRAINT FK_MATRICULA_TURMAS FOREIGN KEY (TUR_INT_ID) REFERENCES TURMAS(TUR_INT_ID)
);