CREATE DATABASE EX10

CREATE TABLE SERVICOS (
  SER_INT_ID INTEGER NOT NULL IDENTITY(1,1),
  SER_STR_DESCRICAO VARCHAR(90),
  SER_INT_VALOR INTEGER,
  CONSTRAINT PK_SER_INT_ID PRIMARY KEY (SER_INT_ID)
);

CREATE TABLE TIPO_DE_QUARTO (
  TIP_INT_ID INTEGER NOT NULL IDENTITY(1,1),
  TIP_STR_DESCRICAO VARCHAR(70),
  CONSTRAINT PK_TIP_INT_ID PRIMARY KEY (TIP_INT_ID)
);

CREATE TABLE CLIENTES (
  CLI_INT_ID INTEGER NOT NULL IDENTITY(1,1),
  CLI_STR_RG VARCHAR(70),
  CLI_STR_RG_2 VARCHAR(70),
  CLI_INT_TELEFONE INTEGER,
  CLI_STR_SEXO CHAR(1),
  CONSTRAINT PK_CLI_INT_ID PRIMARY KEY (CLI_INT_ID)
);

CREATE TABLE QUARTO (
  QUA_INT_ID INTEGER NOT NULL IDENTITY(1,1),
  TIP_INT_ID INTEGER NOT NULL,
  QUA_INT_NUMERO INTEGER,
  QUA_INT_ANDAR INTEGER,
  QUA_STR_DESCRICAO VARCHAR(60),
  QUA_INT_PRECO INTEGER,
  CONSTRAINT PK_QUA_INT_ID PRIMARY KEY (QUA_INT_ID),
  CONSTRAINT FK_QUARTO_TIPO_DE_QUARTO FOREIGN KEY (TIP_INT_ID) REFERENCES TIPO_DE_QUARTO(TIP_INT_ID)
);

CREATE TABLE CLIENTE_SERVICOS_PEDIDO (
  SER_INT_ID INTEGER NOT NULL,
  CLI_INT_ID INTEGER NOT NULL,
  CONSTRAINT FK_CSP_SERVICOS FOREIGN KEY (SER_INT_ID) REFERENCES SERVICOS(SER_INT_ID),
  CONSTRAINT FK_CSP_CLIENTES FOREIGN KEY (CLI_INT_ID) REFERENCES CLIENTES(CLI_INT_ID)
);

CREATE TABLE OCUPACAO (
  OCU_INT_ID INTEGER NOT NULL IDENTITY(1,1),
  QUA_INT_ID INTEGER NOT NULL,
  CLI_INT_ID INTEGER NOT NULL,
  OCU_DAT_ENTRADA DATE,
  OCU_DAT_SAIDA DATE,
  CONSTRAINT PK_OCU_INT_ID PRIMARY KEY (OCU_INT_ID),
  CONSTRAINT FK_OCUPACAO_CLIENTES FOREIGN KEY (CLI_INT_ID) REFERENCES CLIENTES(CLI_INT_ID),
  CONSTRAINT FK_OCUPACAO_QUARTO FOREIGN KEY (QUA_INT_ID) REFERENCES QUARTO(QUA_INT_ID)
);

CREATE TABLE RESERVA (
  RES_INT_ID INTEGER NOT NULL IDENTITY(1,1),
  CLI_INT_ID INTEGER NOT NULL,
  QUA_INT_ID INTEGER NOT NULL,
  RES_DAT_RESERVA DATE,
  RES_INT_QTDE_DIAS INTEGER,
  CONSTRAINT PK_RES_INT_ID PRIMARY KEY (RES_INT_ID),
  CONSTRAINT FK_RESERVA_CLIENTES FOREIGN KEY (CLI_INT_ID) REFERENCES CLIENTES(CLI_INT_ID),
  CONSTRAINT FK_RESERVA_QUARTO FOREIGN KEY (QUA_INT_ID) REFERENCES QUARTO(QUA_INT_ID)
);




